name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  app-url:
    description: 'The URL of your Octomirror app'
    required: true
  server-url:
    description: 'The URL of your GitHub Enterprise Server instance'
    required: true
  pat:
    description: 'The PAT to create orgs, repo and everything else'
    required: true
  init-mode:
    description: 'Non incremental synchronisation mode'
    default: false

outputs:
  organizations:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
